### ISSUE TITLE
Reset cam needed for pic capturing

### ISSUE THREAD

**Issue by philipcaffeine** [microsoft/vision-ai-developer-kit#207]
We tried to get a picture from the camera using the description I found here:
https://github.com/microsoft/vision-ai-developer-kit/tree/master/rest-api-postman-collection
But using 
http://{{hostIp}}:1080/captureimage
works only sporadically and after that, the cam most often needs to be reset

From: Hans Stanglmayr

**Comment by jkubicka** [comment]
Hi @drwill-ms any insight into this?

**Comment by ericwol-msft** [comment]
drwill-ms is out of office until September.

**Comment by mmydland** [comment]
I suspect that this is due to a known issue with the RTSP stream setup. When the VAM is turned on prior to the first capture image, the camera become unstable and usually needs to be restarted.

The workaround is to capture an image (call GET on http://{{hostIp}}:1080/captureimage) before making a call to configure the VAM  (POST on http://{{hostIp}}:1080/vam)

**Comment by drwill-ms** [comment]
Hi, I'm back in the office. I haven't used that API (just committed the Postman API collection created by a colleague), but I think Mark's insight is probably a good direction.

**Comment by jkubicka** [comment]
@mmydland @drwill-ms Do you think a fix will go out for this?

**Comment by jkubicka** [comment]
Closing issue for now, please re-open if issue persists and additional support is needed.
