### ISSUE TITLE
notes on OOTB Vision kit setup includes debugging and setup of the camera to IOTHub

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [microsoft/vision-ai-developer-kit#289]
My notes for the OOTB Vision kit setup includes debugging and setup of the camera to IOTHub. 
Feedback appreciated.  

[NotesOnCameraDebuggingAndSetupMiwilcox010320v2.pdf](https://github.com/microsoft/vision-ai-developer-kit/files/4020273/NotesOnCameraDebuggingAndSetupMiwilcox010320v2.pdf)

**Comment by vasantha-Mindtree** [comment]
@MikeWilcoxMicrosoft  we will look into it and get back to you

**Comment by vasantha-Mindtree** [comment]
Hello @juniem  , @MikeWilcoxMicrosoft  has suggested an update in debugging and setup of the camera to IOTHub documentation. Can you kindly look into this request.

**Comment by PuneetRahejaMS** [comment]
@MikeWilcoxMicrosoft I've tested this and if you have sound on in your laptop you should be able to tell when to press a key to continue. You’ll first hear a sound of USB disconnecting and then reconnecting (when it’s safe to press a key). There have been cases where the USB never reactivates. It’s likely due to an issue with the USB-C cable itself.
