### ISSUE TITLE
Corporate WiFi SSID not found/ browser authentication issue

### ISSUE THREAD

**Issue by Pratheek-Dev** [microsoft/vision-ai-developer-kit#319]
**At home wifi setting**
At home WiFI I have no trouble connecting the cameras to the internet. I am able to connect to the device and set up the wifi by selecting the WiFi SSID of my network from the http://setupaicamera.ms/ webpage.

**While in a corporate Wifi:**
I am trying to install the 3 cameras in a hospital, where they have wifi networks which require you to type in a password into a web browser and agree to their terms/conditions. While on my laptop, I can see the network, join it and a webpage will open asking for the password and agreement checkbox. However, on the Vision AI Camera, I am unable to see that Wifi SSID while configuring the internet via http://setupaicamera.ms/, the WiFI SSID not show up on the drop-down list at all. Also, how can we ensure the Vision AI cameras can get to that corporate webpage to click on the agreements? This is similar to most corporate/retail networks, where they expect you to type in a code or agree to terms of service via a browser pop up before being able to access their network.

**Comment by v-prsasa** [comment]
@Pratheek-Dev We are looking into it.

**Comment by v-ragala** [comment]
@Pratheek-Dev Thank you for providing more information about the hospital corporate network. 
As per your information i got your question. you are able to connect your  camera at your home Wi-Fi mean over the broadband connection and when you came into one of the corporate network they have their own private network which is manageable. At your home which is unmanageable network where we can easily connect our camera. In your case we need to take permission from the corporate network admin and then will can connect.
For corporate network will suggest you to take help from their network admin because it’s under their network security policy we can’t help you on this but we can involve our backend dev team so that they can help you regrading this. 
@jkubicka As per our discussion can you look into it one of our partner having issue to connect camera to the corporate network.

**Comment by jkubicka** [comment]
Hi @Pratheek-Dev Being unable to connect the device to a corporate Wi-Fi network may be due to an existing firewall - you'll need to register the device MAC address with your IT department. The corporate Wi-Fi network should appear in the Wi-Fi drop-down list once it's registered.

**Comment by Pratheek-Dev** [comment]
Thanks @v-ragala @jkubicka . Just wanted to confirm if this will method would also avoid the additional authentication via webpage?

**Comment by jkubicka** [comment]
@Pratheek-Dev Could you please provide a screenshot?

**Comment by MS-Nikunja** [comment]
Hi @Pratheek-Dev, we can continue the discussion here, it will be more easy to track the conversation here. We will wait for you to provide the screenshot.

**Comment by Pratheek-Dev** [comment]
Thanks @MS-Nikunja I've requested the customer to send a screenshot.

**Comment by MS-Nikunja** [comment]
Hi @Pratheek-Dev, Any updates on the issue?

**Comment by Pratheek-Dev** [comment]
Hi @v-ragala @MS-Nikunja I've sent the images to Jan on Teams, he's helping look into this. Keep you posted on this, thanks.

**Comment by v-prsasa** [comment]
@Pratheek-Dev Hey Pratheek, Is this issue resolved?

**Comment by Pratheek-Dev** [comment]
Yeah we have an answer now, thanks
