### ISSUE TITLE
Iotedge daemon version obsolete

### ISSUE THREAD

**Issue by othmane-alaoui** [microsoft/vision-ai-developer-kit#330]
Hello I am having a problem concerning iotedge daemon on the Vision AI Dev Kit. 
After updating the firmware, I run iotedge check and I got the following errors: 
![image](https://user-images.githubusercontent.com/59685366/99375684-4ddd9380-28c4-11eb-9abe-d44e075eeadf.png) 
I can't update the daemon because there is no package manager in Yocto. Is it possible to override the actual Linux image and install a new one that has the iotedge daemon up to date ?

**Comment by v-prsasa** [comment]
@othmane-alaoui yes, you can try that out.

**Comment by othmane-alaoui** [comment]
Thank you @v-prsasa for your answer, is there any tutorial or manual that can help me with that ?

**Comment by v-prsasa** [comment]
@othmane-alaoui We don't have particular tutorial as of now. below link may help you.  
https://azure.github.io/Vision-AI-DevKit-Pages/docs/Get_Started/

**Comment by v-prsasa** [comment]
@othmane-alaoui Should we go ahead and close this case?

**Comment by v-prsasa** [comment]
@othmane-alaoui Can we close this case now? Is the issue resolved?

**Comment by othmane-alaoui** [comment]
@v-prsasa this issue is not resolved yet, I am still looking for a solution

**Comment by v-iskha** [comment]
@othmane-alaoui - 
1. Please find the latest firmware released by Altek for the Vision AI DevKit - https://azure.github.io/Vision-AI-DevKit-Pages/docs/Firmware/
2. In order to communicate with the Vision AI DevKit using a command line, including updating the firmware when needed, you will need the Android SDK Platform Tools. The Vision AI DevKit specifically uses the Android Debug Bridge (ADB) and Fastboot - https://azure.github.io/Vision-AI-DevKit-Pages/docs/platform_tools/
3. Use this guide for setting up Azure resources - https://azure.github.io/Vision-AI-DevKit-Pages/docs/Setup_Azure_resources/

**Comment by v-iskha** [comment]
Closing this case as we don't see any response since past 14 days.
